version: '3'

services:

  logstash:
    image: logstash:6.8.3
    volumes:
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./pipeline:/usr/share/logstash/pipeline
    links:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:6.8.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    links:
      - kibana

  kibana:
    image: kibana:6.8.3
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601

volumes:
  esdata:
    driver: local
